# ./.default_config.toml

[game]
screen_width = 800
screen_height = 600
gravity = 0.5
fps = 60

[player]
initial_x = 50
initial_y = 300
width = 30
height = 50
move_speed = 5
jump_strength = 12
double_jump_strength = 10
initial_liberty_shields = 5
invincible_duration = 120  # frames
flash_interval = 10  # frames

[level]
scroll_speed = 2
floor_height = 50
hole_chance = 0.1
hole_min_width = 30
hole_max_width = 80
platform_chance = 0.7
min_platform_height = 200
max_platform_height = 400
block_min_width = 50
block_max_width = 150
block_min_height = 20
block_max_height = 80
min_blocks = 5
min_source_codes = 5
max_jump_distance = 120  # Maximum horizontal distance for a jump

[source_code]
width = 20
height = 20

[colors]
background = [135, 206, 235]  # Sky blue
player = [255, 0, 0]  # Red
block = [0, 128, 0]  # Green
floor = [139, 69, 19]  # Brown
source_code = [255, 255, 0]  # Yellow
text = [255, 255, 255]  # White

[fonts]
hud_size = 24
main_size = 36
game_over_size = 72