[player]
initial_liberty_shields = 5
move_speed = 5
jump_strength = -15
initial_x = 100
initial_y = 300
width = 40
height = 60

[game]
screen_width = 800
screen_height = 600
fps = 60
gravity = 0.8

[level]
scroll_speed = 2
min_blocks = 5
min_source_codes = 3
block_min_width = 50
block_max_width = 150
block_min_height = 20
block_max_height = 60
floor_height = 40
hole_chance = 0.2
hole_min_width = 80
hole_max_width = 160

[source_code]
width = 20
height = 20

[colors]
background = [135, 206, 235]
player = [255, 0, 0]
block = [100, 100, 100]
floor = [34, 139, 34]
source_code = [255, 255, 0]
text = [255, 255, 255]

[fonts]
main_size = 36
hud_size = 24